name: Build Windows EXE

on: [push] # Сборка будет запускаться автоматически при каждом git push

jobs:
  build:
    runs-on: windows-latest # Запуск на сервере Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Указываем вашу версию Python (как в логах — 3.12)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Устанавливаем все библиотеки для вашего кликера
        # Примечание: evdev исключен, так как мы собираем под Windows
        pip install pynput Pillow PySide6 pywebview pyinstaller

    - name: Build EXE via PyInstaller
      run: |
        # --onefile: собирает всё в один exe
        # --noconsole: отключает фоновое окно консоли (кликер запустится как чистое GUI приложение)
        # --add-data "icon.svg;.": упаковывает иконку внутрь exe
        # --icon="icon.svg": устанавливает иконку для самого .exe файла в проводнике Windows
        pyinstaller --onefile --noconsole --add-data "icon.ico;." --icon="icon.ico" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: clicker-windows-app
        path: dist/main.exe # Путь, куда PyInstaller положит готовый файл
