name: Build Windows EXE

on: [push] # Собирать при каждом пуше в репозиторий

jobs:
  build:
    runs-on: windows-latest # Запуск на сервере Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-python-version: '3.11' # Укажите вашу версию

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install eel pynput Pillow PySide6 pywebview pyinstaller
        # Примечание: evdev убираем, так как он работает ТОЛЬКО на Linux

    - name: Build EXE
      run: |
        pyinstaller --onefile --noconsole --add-data "web;web" main.py
        # Обратите внимание: на Windows в --add-data используется точка с запятой (;), а не двоеточие (:)

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-app
        path: dist/main.exe
